#!/bin/sh

# x server specific
xrdb -merge ${HOME}/.config/X11/xresources
xset b off &
xset r rate 500 90 &

# execute the startup programs/settings
unclutter -noevents -onescreen &
sxhkd &
clipmenud &
xwallpaper --zoom ${XDG_DATA_HOME}/wallpaper.png &
pipewire &
pipewire-pulse &
picom --experimental-backends &
redshift &
dwmblocks &
exec dwm
