#!/bin/sh

# x server specific
xrdb -merge ${HOME}/.config/X11/xresources
xset b off &
xset r rate 500 90 &

# execute the startup programs/settings
sxhkd &
clipmenud &
xwallpaper --zoom ${XDG_DATA_HOME}/wallpaper.png &
pipewire 1>/dev/null 2>&1 &
pipewire-pulse 1>/dev/null 2>&1 &
picom --experimental-backends 1>/dev/null 2>&1 &
redshift &
dwmblocks &
xbanish -s &
exec dwm
