#!/usr/bin/env bash

# bar module
# display and update when cycling through hlwm tags
# copied from: https://gist.github.com/olmokramer/b28ff8ed5fd366e3ebb23b79915ec850

hash herbstclient xrandr

print_tags() {
	for tag in $(herbstclient tag_status "$1"); do
		name=${tag#?}
		state=${tag%$name}
		case "$state" in
		'#')
			printf '%%{F#90999c}%%{+u}   %s   %%{F-}%%{-u}' "$name"
			;;
		'+')
			printf '%%{F#90999c}   %s   %%{F-}' "$name"
			;;
		'!')
			printf '%%{B#121313}%%{F#fefae0}%%{u#c4501b}%%{+u}   %s   %%{-u}%%{F-}%%{B-}' "$name"
			;;
		'.')
			printf '%%{F#4d4e4c}   %s   %%{F-}' "$name"
			;;
		*)
			printf '   %s   ' "$name"
		esac
	done
	printf '\n'
}

geom_regex='[[:digit:]]\+x[[:digit:]]\++[[:digit:]]\++[[:digit:]]\+'
geom=$(xrandr --query | grep "^$MONITOR" | grep -o "$geom_regex")
monitor=$(herbstclient list_monitors | grep "$geom" | cut -d: -f1)

print_tags "$monitor"

IFS="$(printf '\t')" herbstclient --idle | while read -r hook; do
	case "$hook" in
	tag*)
		print_tags "$monitor"
		;;
	esac
done
