#!/usr/bin/env bash

# misc
# save and restore frame layouts using a menu(rofi)

hc() { herbstclient "$@" ;}

declare -a options=( 'dump' 'restore' )
layout_dir="${HOME}/.config/herbstluftwm/layouts"
[ ! -d "$layout_dir" ] && mkdir "$layout_dir"

chosen="$(printf '%s\n' "${options[@]}" | rofi -dmenu -i -p 'select: ')"
case "$chosen" in
    'dump')
        read -r layout_name <<< $(rofi -dmenu -p 'layout name: ')
        hc dump > "$layout_dir"/"$layout_name"
    ;;
    'restore')
        declare -a available_layouts=(); declare -i i=0
        for layout in "$layout_dir"/*; do
            [ -f "$layout" ] || continue
            available_layouts[$i]="$layout"
            (( i++ ))
        done
        [ ${#available_layouts[@]} -eq 0 ] && notify-send 'no layouts available' && exit
        chosen_layout="$(printf '%s\n' "${available_layouts[@]/${layout_dir}\/}" \
            | rofi -dmenu -i -p 'layout to restore: ')"
        [ -z "$chosen_layout" ] || hc load "$(cat "$layout_dir"/"$chosen_layout")"
    ;;
    *) exit ;;
esac

