#!/usr/bin/env bash

# Switch to a project in a new tmux session.
# Inspiration from ThePrimeagen's tmux-sessionizer.
#
# Dependencies: fd, zoxide, fzf

export PROJECTS="${PROJECTS:=$HOME/Dev}"

exclude=() # append directories to be excluded
exclude_fpath="$HOME/.cache/tpr.exclude"

# if [ ! -f "$exclude_fpath" ] || [ "$(tail -n1 "$exclude_fpath")" != "${exclude[-1]}" ]; then
#   printf '%s\n' "${exclude[@]}" >"$exclude_fpath"
# fi

# Project directories are sorted by their frecency rate using zoxide.
# To populate the zoxide database with all the project directory entries,
# run: fd --type d --max-depth <depth> . $PROJECTS | xargs -n1 zoxide add
# The "--max-depth" count depends on how the root directory is structured.
#
# Using input as array for capturing optional keypresses(e.g. with fzf --expect)
readarray -t input < <(fd --type d --max-depth 1 . $PROJECTS |
  while read -r p; do
    zoxide query -ls "$p"
  done |
  sed "s:${PROJECTS}/::" |
  sort -nr |
  fzf --no-sort |
  awk '{print $2}')

case "${#input[@]}" in
  1)
    project=${input[0]}
    ;;
  2)
    project=${input[1]}
    ;;
  *)
    exit
    ;;
esac

session_name="${project##[a-zA-Z]*/}"

if [ -z "$(pgrep tmux)" ]; then
  tmux new -s "$session_name" -c "$PROJECTS/$project"
elif ! tmux has-session -t "$session_name" 2>/dev/null; then
  tmux new -ds "$session_name" -c "$PROJECTS/$project"
fi

# Increment the rank of the selected project and switch to it
zoxide add -s 1 "$PROJECTS/$project" && tmux switchc -t "$session_name"
