#!/bin/sh

# general
alias ll="ls --group-directories-first --sort=version --time-style='+%m-%d %I:%M%p' -lGh "
alias la="ls --group-directories-first --sort=version --time-style='+%m-%d %I:%M%p' -alGh"
alias clr="clear && cd"
alias rm="rm -iv"
alias cp="cp --preserve=all -Riv"
alias mv="mv -iv"
alias rg="rg --colors 'path:fg:green' --colors 'match:fg:yellow' --colors 'line:fg:245'"
alias grep="grep --color=auto"

# git
alias gst="git status"
alias gdf="git diff"
alias glg="git log"
alias gck="git checkout"

# neovim
alias nv="nvim ."

# other
alias termcolors="curl -s https://gist.githubusercontent.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263/raw/ | bash"
alias pkgi="pacman -Qn | awk '{print $1}' | fzf --header='installed packages(native)' --preview='pacman -Qi {1}'"
alias up="doas pacman -Syu"
