[colors.primary]
background = "#0f0f10"
foreground = "#e1d9ea"

[colors.normal]
black = "#222827"
red = "#725478"
green = "#63b0b0"
yellow = "#9898ae"
blue = "#5786bc"
magenta = "#684c9a"
cyan = "#7da2a9"
white = "#e6ebe5"

[colors.bright]
black = "#5d6f74"
red = "#cd749c"
green = "#94dbf4"
yellow = "#c0c0dd"
blue = "#daf3f3"
magenta = "#9c75dd"
cyan = "#a9d1df"
white = "#d9d6cf"
