#!/usr/bin/env zsh

# Function to clone and source zsh plugins,
# as suggested by: Christian Chiarulli

export _ZPLUGDIR="${XDG_DATA_HOME}/zsh/plugins/"
[ ! -d "$_ZPLUGDIR" ] && mkdir -p "$_ZPLUGDIR"

function zsh_add() {
  [ -f "${_ZPLUGDIR}/$1" ] && source "${_ZPLUGDIR}/$1"
}

function zsh_plug() {
  plugin_name="${1##*\/}"
  if [ -d "${_ZPLUGDIR}/${plugin_name}" ]; then
    zsh_add "${plugin_name}/${plugin_name}.plugin.zsh" || zsh_add "${plugin_name}/${plugin_name}.zsh"
  else
    printf '%s\n' "Cloning plugin $plugin_name to $_ZPLUGDIR ..."
    git clone --quiet "https://github.com/$1.git" "${_ZPLUGDIR}/$plugin_name"
    printf '%s\n' "Done! (open a new session for the plugin to take effect)"
  fi
}
