#!/usr/bin/env bash

# configuration file for herbstluftwm

hc() { herbstclient "$@" ;}
hc emit_hook reload
# enable down padding for displaying bar at the bottom
hc pad 0 0 0 35 0

# tags
tag_names=( {1..5} )
tag_keys=( {1..5} 0 )

# Keybindings
hc keyunbind --all
Mod=Mod4

hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close

# basic movement in tiling and floating mode
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   top     0.5
hc keybind $Mod-o       split   right   0.5

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# select/cycle through tags
hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done
hc keybind $Mod-period  use_index +1 --skip-visible
hc keybind $Mod-comma   use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
# cycle through the available layouts within a frame
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
                     . emit_hook chlayout                                       \
               , and . cycle_layout +1 . emit_hook chlayout

# focus
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-n cycle
hc keybind $Mod-i jumpto urgent

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# custom scripts
scrpath="${XDG_CONFIG_HOME}/herbstluftwm/scripts"
hc keybind $Mod-Shift-q spawn "$scrpath"/kb-rmclients

# Appearance
active_color="#6b6f63"
normal_color="#232729"

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc attr theme.title_color           "$active_color"
hc attr theme.normal.title_color    "$normal_color"
hc attr theme.title_height 16
hc attr theme.padding_top 7
hc attr theme.title_font 'Liberation Sans:pixelsize=12'

# options
hc set frame_gap 4
hc set frame_padding 4
hc set frame_border_width 0
hc set frame_bg_transparent on
hc set frame_border_active_color    "$active_color"
hc set frame_border_normal_color    "#00000000"

hc set window_gap 8
hc set window_border_width 0
hc attr theme.floating.border_width 2
hc set window_border_active_color   "$active_color"
hc set window_border_normal_color   "$normal_color"

hc set always_show_frame off
hc set smart_frame_surroundings on
hc set smart_window_surroundings off
hc set mouse_recenter_gap 0
hc set tree_style '╾│ ├└╼─┐'

# rules
hc unrule -F
# normally focus new clients
hc rule focus=on
hc rule floatplacement=center

# window rules
#hc rule class=XTerm tag=3 # move all xterms to tag 3
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule class='Nsxiv' instance='wallpapers' floating=on
hc rule class='pinentry-qt' floating=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

# using polybar as status displayer
statusbar() {
    polybar --config="${HOME}/.config/herbstluftwm/bar_config.ini" hl_status 2>&1 | tee --append /tmp/polybar.log & disown
}
pgrep -x polybar || statusbar

