#!/usr/bin/env bash

# kill every client except the focused one

hc() { herbstclient "$@" ;}

IFS=$'\t' read -ra taglist <<< "$(hc tag_status)"

for tag in "${taglist[@]}"; do
    case "${tag:0:1}" in
        '#')
            active_tag="${tag:1}"
            ;;
        *)
            continue
            ;;
    esac
done

IFS=' ' read -ra clientlist <<< "$(hc list_clients --tag="$active_tag" | tr '\n' ' ')"
for (( i=0; i < ${#clientlist[@]}; i++ )); do
    if hc compare clients.focus.winid = "${clientlist[$i]}"; then
        continue
    else
        hc close "${clientlist[$i]}"
    fi
done
