set -g default-terminal "xterm-ghostty"
set -sa terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set -sa terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -g allow-passthrough on

set -g mouse on
set -g escape-time 10
set -g repeat-time 600
set -g history-limit 5000

set -g focus-events on
set -g detach-on-destroy off
set -g renumber-windows on
set -g base-index 1
set -g pane-base-index 1

# decoration
set -g status on
set -g status-interval 5
set -g status-position bottom
set -g status-justify left
set -g status-left-length 50

set -g status-style bg=default
set -g status-left '#[fg=grey][#S]#[bg=default]#{?client_prefix,#[fg=grey] P,} '
set -g status-right '#[fg=grey]#H | #(pmset -g batt | grep -Eo "\d+%%")'

set -g pane-border-style fg='#222827'
set -g pane-active-border-style fg=grey

setw -g window-status-style fg=grey,bg=default
setw -g window-status-current-style fg='#7da2a9',bg=default

set -g message-style fg='#7da2a9'
set -g mode-style bg='#152f38'

# keybinds
unbind 'C-b'
set -g prefix 'C-q'
bind -r 'C-q' send-prefix
setw -g mode-keys vi
set -g status-keys vi

unbind -T copy-mode-vi MouseDragEnd1Pane
bind -T copy-mode-vi 'v' send-keys -X begin-selection
bind -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "pbcopy"

bind 'h' select-pane -L
bind 'j' select-pane -D
bind 'k' select-pane -U
bind 'l' select-pane -R
bind ';' last-pane -Z
bind 'o' kill-pane -a
bind 'O' kill-window -a
bind 'b' break-pane -a
bind -n C-up resize-pane -U 3
bind -n C-down resize-pane -D 3
bind -n C-left resize-pane -L 7
bind -n C-right resize-pane -R 7

bind '-' split-window -v -c "#{pane_current_path}"
bind '\' split-window -h -c "#{pane_current_path}"
bind 'C' new-window -c "#{pane_current_path}"
bind -r > swap-window -d -t :+
bind -r < swap-window -d -t :-

bind C-h set -g status
bind S command-prompt -p "New Session:" "new -A -s '%%' -c '~'"
bind C-r source-file ~/.config/tmux/tmux.conf \; display "Reloaded tmux config!"

bind C-p neww -n "projects" "tmux_switchp"
if -b '[ "$TERMINAL" = "alacritty" ]' {
    bind C-t run "$HOME/.config/alacritty/opacity.sh"
}
