add_newline = true

[line_break]
disabled = false

[env_var]
disabled = true

[username]
disabled = true

[hostname]
ssh_only = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[directory]
truncation_length = 3
truncation_symbol = '.../'
format = "in [$path]($style) "
style = "blue"

[git_branch]
format = "on branch [$symbol$branch]($style) "
symbol = "#"
style = "fg:#e4627e bold italic"

