[colors.primary]
background = "#0f0f10"
foreground = "#726464"

[colors.normal]
black = "#0f0f10"
blue = "#42647f"
cyan = "#63b0b0"
green = "#3c7153"
magenta = "#654a96"
red = "#d19299"
white = "#e8f4e7"
yellow = "#bbc373"

[colors.bright]
black = "#796769"
blue = "#3788a2"
cyan = "#89d9d0"
green = "#609f83"
magenta = "#caade1"
red = "#dfb8bc"
white = "#ffffff"
yellow = "#dad36d"

