#!/usr/bin/env zsh

# function to serch for package info using fzf
function pkgi() {
    os="$(grep "^ID" /etc/os-release | cut -d'=' -f2)"

    case "$os" in
        'arch')
	    pacman -Qn | awk '{print $1}' | fzf --header='installed packages(native)' --preview='pacman -Qi {1}' ;;
	'"void"')
	    xbps-query -l | awk '{print $2}' | fzf --header='installed packages' --preview='xbps-query -S {1}' ;;
    esac
}
